name: Build on Commit

on:
  push:
    branches:
      - master # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci  # Or yarn install --frozen-lockfile

      - name: Build
        run: npm run build  # Or yarn build

      - name: Create branch
        run: |
          git config --global user.name 'amatter23'
          git config --global user.email 'matterahmed36@gmail.com'
          git checkout -b build-branch
          git rm -rf .  # Remove all files in the branch
          git checkout main -- .htaccess  # Copy .htaccess file from main branch
          git add -f build .htaccess  # Add the build folder/files and .htaccess file
          git commit -m 'Add build files'

      - name: Push branch to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-branch