name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if build branch exists
        run: |
          if [[ -d $GITHUB_WORKSPACE/.git && -z "$(git -C $GITHUB_WORKSPACE branch --list build-branch)" ]]; then
            echo "build-branch already exists."
            exit 0
          else
            git init $GITHUB_WORKSPACE
            git -C $GITHUB_WORKSPACE checkout -b build-branch
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build  # Or yarn build


      - name: Copy build files to build-branch
        run: |
          mkdir -p build-branch
          cp -r build/* build-branch/
          cp .gitignore build-branch/

      - name: Commit and push changes
        run: |
          git -C $GITHUB_WORKSPACE add build-branch
          git -C $GITHUB_WORKSPACE add .gitignore
          git -C $GITHUB_WORKSPACE config --local user.email "matterahmed36@gmail.com"
          git -C $GITHUB_WORKSPACE config --local user.name "amatter23"
          git -C $GITHUB_WORKSPACE commit -m "Add build files to build-branch"
          git -C $GITHUB_WORKSPACE remote add origin <repository-url>
          git -C $GITHUB_WORKSPACE push origin build-branch