name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  BUILD_BRANCH: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if build branch exists
        run: |
          if ! git show-ref --quiet "refs/heads/${BUILD_BRANCH}"; then
            git checkout -b ${BUILD_BRANCH}
          fi

      - name: Build project
        run: npm install && npm run build

      - name: Copy build files to build branch
        run: |
          mkdir -p ${BUILD_BRANCH}
          find build -type f -not -path "build/.gitignore" -exec cp -n {} ${BUILD_BRANCH} \;
          rm -rf ${BUILD_BRANCH}/build

      - name: Update .htaccess
        run: cp .htaccess ${BUILD_BRANCH}/.htaccess

      - name: Ignore files except build directory
        run: |
          echo "!${BUILD_BRANCH}/" >> .gitignore
          echo "*" >> .gitignore
          echo "!${BUILD_BRANCH}/.gitignore" >> .gitignore

      - name: Copy build files to build branch
        run: |
          mkdir -p ${BUILD_BRANCH}
          cp -R build/. ${BUILD_BRANCH}
          cp .htaccess ${BUILD_BRANCH}/.htaccess