name: Build on Commit

on:
  push:
    branches:
      - master # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci  # Or yarn install --frozen-lockfile

      - name: Build
        run: npm run build  # Or yarn build

      - name: Create branch if it doesn't exist
        id: create-branch
        run: |
          git config --global user.name 'amatter23'
          git config --global user.email 'matterahmed36@gmail.com'
          git rev-parse --verify build-branch || git checkout -b build-branch

      - name: Reset branch to main
        if: steps.create-branch.outputs.branch-exists != 'true'  # Only reset if branch doesn't exist
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Copy build files to branch
        run: |
          rm -rf build-branch/*
          cp -R build/* build-branch/

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m 'Update build files'
          git push origin build-branch