name: Build

on:
  push:
    branches:
      - master  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if build branch exists
        run: |
          if git rev-parse --verify --quiet build-branch; then
            echo "build-branch already exists."
            exit 0
          else
            git checkout -b build-branch
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build files to build-branch
        run: |
          mkdir -p build-branch
          cp -r build/* build-branch/
          cp .gitignore build-branch/

      - name: Commit and push changes
        run: |
          git add build-branch
          git add .gitignore
          git config --local user.email "matterahmed36@gmail.com"
          git config --local user.name "amatter23"
          git commit -m "Add build files to build-branch"
          git push origin build-branch