name: Build on Commit

on:
  push:
    branches:
      - master # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci  # Or yarn install --frozen-lockfile

      - name: Build
        run: npm run build  # Or yarn build

      - name: Check if branch exists
        id: branch-check
        run: |
          set -e
          if git ls-remote --exit-code . "refs/heads/build-branch"; then
            echo "Branch exists"
            echo "::set-output name=branch-exists::true"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch-exists::false"
          fi

      - name: Create branch
        run: |
          git config --global user.name 'amatter23'
          git config --global user.email 'matterahmed36@gmail.com'
          git checkout -b build-branch
          git rm -rf .  # Remove all files in the branch
          git add -f build  # Add the build folder/files
          git commit -m 'Update build files'

      - name: Push branch to GitHub
        if: steps.branch-check.outputs.branch-exists == 'true'  # Only push if branch exists
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-branch