name: Build on Commit

on:
  push:
    branches:
      - master  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci  # Or yarn install --frozen-lockfile

      - name: Build
        run: npm run build  # Or yarn build

      - name: Create branch if it doesn't exist
        id: create-branch
        run: |
          git config --global user.name 'amatter23'
          git config --global user.email 'matterahmed36@gmail.com'
          git rev-parse --verify build-branch || git checkout -b build-branch

      - name: Create build directory
        run: |
          mkdir -p build-branch

      - name: Copy build files to branch
        run: |
          cp -R build/. build-branch/
          cp .htaccess build-branch/

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m 'Update build files'
          git pull origin build-branch --rebase
          git push origin build-branch